---
- name: Copy file with reader allow reads permissions
  tasks:
   - hosts: localhost
     become: true
     name: provide o+r privileges for source
      - file:
        path: /home/ubuntu/foo.conf
        mode: o+r

   - hosts: test
     become: yes
     copy:
       src: /home/ubuntu/foo.conf
       dest: /etc/foo.conf
       owner: foo
       group: foo
       mode: '0644'
